---
abstract: 'The great new AnyEvent::SMTP!'
author:
  - 'Pedro Melo <melo@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-SMTP
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  Mouse: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
